package com.pharos.compliance.transaction.model;

public enum TransactionMetric {
  ALL,
  SELECTED,
  ATTEMPTS_FOUND,
  MISSING,
  EXPECTED_ELIGIBLE,
  ACTUAL_ELIGIBLE,
  TRANSFORMED,
  FAILED,
  EXPECTED_REPORTABLE,
  ACTUAL_REPORTABLE,
  EXCLUDED,
  FILTRATION_VARIANCE,
  RECONCILIATION_VARIANCE,
  TRANSFORMER_OUTPUT
}
