#!/usr/bin/env python3
"""Load reg_reportable_activity.json into pharos.reg_reportable_activity.

This table holds full sender/receiver reportable-activity detail (party,
address, ID, and bank fields) keyed by txn_sur_key -- the validated
txn_sur_key <-> rule_hit.external_txn_key identifier pair. All 303
DDL columns are loaded; COLUMNS below must stay in sync with
database/sqlScripts/ddl.sql if that table is ever altered.
"""

from pathlib import Path

from loader_common import build_parser, read_json_rows, run_loader


TABLE = "pharos.reg_reportable_activity"
DEFAULT_FILE = Path(__file__).resolve().parents[1] / "mockData" / "reg_reportable_activity.json"
REQUIRED_COLUMNS = ("txn_sur_key",)

COLUMNS = (
    "txn_sur_key",
    "associated_mtcn",
    "associated_txn_sur_key",
    "bl_customer_verification_source",
    "group_mtcn",
    "group_send_date",
    "latest_attempt_time",
    "mtcn",
    "mtcn10",
    "pa_intended_pay_out",
    "pa_pay_brand",
    "pa_pay_channel",
    "pa_pay_in",
    "pa_pay_out",
    "pa_pay_product_code",
    "pa_product",
    "pa_recording_channel",
    "pa_send_brand",
    "pa_send_product_code",
    "pa_send_speed_of_delivery",
    "r3_party_address_line_2",
    "r3_party_city",
    "r3_party_country",
    "r3_party_date_of_birth",
    "r3_party_id_number",
    "r3_party_indorgflag",
    "r3_party_name",
    "r3_party_name_1",
    "r3_party_name_2",
    "r3_party_name_3",
    "r3_party_nationality",
    "r3_party_occupation",
    "r3_party_phone_number",
    "r3_party_place_of_birth",
    "r3_party_state",
    "r3_party_zip_code",
    "r_3rd_party_address_line_1",
    "r_act_on_others_behalf",
    "r_act_on_own_behalf",
    "r_agent_country",
    "r_agent_id",
    "r_agent_network_id",
    "r_agent_operator_name_1",
    "r_agent_operator_name_2",
    "r_agent_operator_name_3",
    "r_attempt_id",
    "r_bank_city",
    "r_bank_code",
    "r_bank_name",
    "r_city",
    "r_cpc_currency_code",
    "r_currency",
    "r_date",
    "r_electronic_validation",
    "r_fx_feed_date",
    "r_fx_feed_id",
    "r_ip_address",
    "r_local_principal",
    "r_party_address_line_1",
    "r_party_address_line_2",
    "r_party_bank_account_number",
    "r_party_base_mobile_phone",
    "r_party_base_mobile_phone_prefix",
    "r_party_base_phone_number",
    "r_party_base_phone_number_prefix",
    "r_party_city",
    "r_party_city_of_birth",
    "r_party_country_of_birth",
    "r_party_country_of_residence",
    "r_party_date_of_birth",
    "r_party_email_address",
    "r_party_employer",
    "r_party_galactic_id",
    "r_party_gender",
    "r_party_id2_exp_date",
    "r_party_id2_issue_date",
    "r_party_id2_issuing_country",
    "r_party_id2_number",
    "r_party_id2type",
    "r_party_id3_number",
    "r_party_id3type",
    "r_party_id_expiration_date",
    "r_party_id_issue_date",
    "r_party_id_issuer_country",
    "r_party_id_issuing_agency",
    "r_party_id_issuing_authority_1",
    "r_party_id_number",
    "r_party_id_type",
    "r_party_issuing_authority",
    "r_party_mobile_phone",
    "r_party_name",
    "r_party_name_1",
    "r_party_name_2",
    "r_party_name_3",
    "r_party_name_4",
    "r_party_nationality",
    "r_party_nature_of_work",
    "r_party_occupation",
    "r_party_pcp_number",
    "r_party_phone_number",
    "r_party_place_of_birth",
    "r_party_relationship",
    "r_party_state_province",
    "r_party_status_of_employment",
    "r_party_zipcode_postalcode",
    "r_province",
    "r_purpose_of_transaction",
    "r_routing_number",
    "r_source_of_funds",
    "r_template",
    "r_time",
    "r_us_principal",
    "refund_flag",
    "s3_party_address_line_2",
    "s3_party_city",
    "s3_party_country",
    "s3_party_date_of_birth",
    "s3_party_id_number",
    "s3_party_indorgflag",
    "s3_party_name",
    "s3_party_name_1",
    "s3_party_name_2",
    "s3_party_name_3",
    "s3_party_nationality",
    "s3_party_occupation",
    "s3_party_phone_number",
    "s3_party_place_of_birth",
    "s3_party_state",
    "s3_party_zip_code",
    "s_3rd_party_address_line_1",
    "s_act_on_others_behalf",
    "s_act_on_own_behalf",
    "s_agent_country",
    "s_agent_id",
    "s_agent_network_id",
    "s_agent_operator_name_1",
    "s_agent_operator_name_2",
    "s_agent_operator_name_3",
    "s_attempt_id",
    "s_bank_city",
    "s_bank_code",
    "s_bank_name",
    "s_city",
    "s_counter_party_address_line_1",
    "s_counter_party_address_line_2",
    "s_counter_party_city",
    "s_counter_party_country",
    "s_counter_party_state",
    "s_counter_party_zipcode_postalcode",
    "s_cpc_currency_code",
    "s_currency",
    "s_date",
    "s_electronic_validation",
    "s_fx_feed_date",
    "s_fx_feed_id",
    "s_intended_bank_city",
    "s_intended_bank_code",
    "s_intended_bank_name",
    "s_intended_city",
    "s_intended_country",
    "s_intended_party_address_line_1",
    "s_intended_party_address_line_2",
    "s_intended_party_bank_acct_num",
    "s_intended_party_city",
    "s_intended_party_country_of_res",
    "s_intended_party_email_address",
    "s_intended_party_mobile_phone",
    "s_intended_party_name",
    "s_intended_party_name_1",
    "s_intended_party_name_2",
    "s_intended_party_name_3",
    "s_intended_party_name_4",
    "s_intended_party_state_province",
    "s_intended_party_zipcode_postalcode",
    "s_intended_routing_number",
    "s_ip_address",
    "s_local_charges",
    "s_local_principal",
    "s_party_address_line_1",
    "s_party_address_line_2",
    "s_party_bank_account_number",
    "s_party_base_mobile_phone",
    "s_party_base_mobile_phone_prefix",
    "s_party_base_phone_number",
    "s_party_base_phone_number_prefix",
    "s_party_cc_number",
    "s_party_city",
    "s_party_city_of_birth",
    "s_party_country_of_birth",
    "s_party_country_of_residence",
    "s_party_date_of_birth",
    "s_party_email_address",
    "s_party_employer",
    "s_party_galactic_id",
    "s_party_gender",
    "s_party_id2_exp_date",
    "s_party_id2_issue_date",
    "s_party_id2_issuing_country",
    "s_party_id2_number",
    "s_party_id2type",
    "s_party_id3_number",
    "s_party_id3type",
    "s_party_id_expiration_date",
    "s_party_id_issue_date",
    "s_party_id_issuer_country",
    "s_party_id_issuing_agency",
    "s_party_id_issuing_authority_1",
    "s_party_id_number",
    "s_party_id_type",
    "s_party_issuing_authority",
    "s_party_mobile_phone",
    "s_party_name",
    "s_party_name_1",
    "s_party_name_2",
    "s_party_name_3",
    "s_party_name_4",
    "s_party_nationality",
    "s_party_nature_of_work",
    "s_party_occupation",
    "s_party_pcp_number",
    "s_party_phone_number",
    "s_party_place_of_birth",
    "s_party_relationship",
    "s_party_state_province",
    "s_party_status_of_employment",
    "s_party_zipcode_postalcode",
    "s_province",
    "s_purpose_of_transaction",
    "s_routing_number",
    "s_source_of_funds",
    "s_template",
    "s_time",
    "s_us_charges",
    "s_us_principal",
    "sub_status",
    "txn_status",
    "urb_force_pay_flag",
    "urb_indicator",
    "created_timestamp",
    "modified_timestamp",
    "s_party_addr_verif_doc_issuing_authority",
    "r_party_addr_verif_doc_issuing_authority",
    "s_party_addr_verif_doc_issue_date",
    "r_party_addr_verif_doc_issue_date",
    "s_party_addr_verif_doc_number",
    "r_party_addr_verif_doc_number",
    "s_party_addr_verif_doc_type",
    "r_party_addr_verif_doc_type",
    "s_party_id2_issuer_authority",
    "r_party_id2_issuer_authority",
    "s_party_id3_issuing_country",
    "r_party_id3_issuing_country",
    "s_party_id3_issue_date",
    "r_party_id3_issue_date",
    "s_party_id3_exp_date",
    "r_party_id3_exp_date",
    "s_party_id3_issuer_authority",
    "r_party_id3_issuer_authority",
    "s_intended_party_base_phone_number_prefix",
    "s_intended_party_base_phone_number",
    "s_intended_party_base_mobile_phone_prefix",
    "s_intended_party_base_mobile_phone",
    "s_intended_party_phone_number",
    "s_intended_agent_country",
    "s_intended_party_occupation",
    "s_intended_party_nationality",
    "s_intended_party_galactic_id",
    "s_intended_party_date_of_birth",
    "r_party_bank_account_type",
    "s_account_holder_name",
    "r_account_holder_name",
    "s_intended_account_holder_name",
    "s_merchant_id",
    "r_merchant_id",
    "s_merchant_cat",
    "r_merchant_cat",
    "s_merchant_name",
    "r_merchant_name",
    "s_merchant_address",
    "r_merchant_address",
    "s_merchant_city",
    "r_merchant_city",
    "s_merchant_state",
    "r_merchant_state",
    "s_merchant_zip",
    "r_merchant_zip",
    "s_merchant_country",
    "r_merchant_country",
    "s_txn_desc_1",
    "r_txn_desc_1",
    "s_txn_desc_2",
    "r_txn_desc_2",
    "transaction_code",
    "transaction_number",
    "s_intended_party_bank_name",
    "s_intended_party_bank_city",
    "s_intended_party_routing_number",
    "s_wueco_flag",
    "r_wueco_flag",
    "s_state_of_birth",
    "r_state_of_birth",
    "s_bank_account_number_2",
    "r_bank_account_number_2"
)

UPSERT = """
INSERT INTO pharos.reg_reportable_activity (
    txn_sur_key, associated_mtcn, associated_txn_sur_key,
    bl_customer_verification_source, group_mtcn, group_send_date, latest_attempt_time,
    mtcn, mtcn10, pa_intended_pay_out, pa_pay_brand, pa_pay_channel, pa_pay_in,
    pa_pay_out, pa_pay_product_code, pa_product, pa_recording_channel, pa_send_brand,
    pa_send_product_code, pa_send_speed_of_delivery, r3_party_address_line_2,
    r3_party_city, r3_party_country, r3_party_date_of_birth, r3_party_id_number,
    r3_party_indorgflag, r3_party_name, r3_party_name_1, r3_party_name_2,
    r3_party_name_3, r3_party_nationality, r3_party_occupation, r3_party_phone_number,
    r3_party_place_of_birth, r3_party_state, r3_party_zip_code,
    r_3rd_party_address_line_1, r_act_on_others_behalf, r_act_on_own_behalf,
    r_agent_country, r_agent_id, r_agent_network_id, r_agent_operator_name_1,
    r_agent_operator_name_2, r_agent_operator_name_3, r_attempt_id, r_bank_city,
    r_bank_code, r_bank_name, r_city, r_cpc_currency_code, r_currency, r_date,
    r_electronic_validation, r_fx_feed_date, r_fx_feed_id, r_ip_address,
    r_local_principal, r_party_address_line_1, r_party_address_line_2,
    r_party_bank_account_number, r_party_base_mobile_phone,
    r_party_base_mobile_phone_prefix, r_party_base_phone_number,
    r_party_base_phone_number_prefix, r_party_city, r_party_city_of_birth,
    r_party_country_of_birth, r_party_country_of_residence, r_party_date_of_birth,
    r_party_email_address, r_party_employer, r_party_galactic_id, r_party_gender,
    r_party_id2_exp_date, r_party_id2_issue_date, r_party_id2_issuing_country,
    r_party_id2_number, r_party_id2type, r_party_id3_number, r_party_id3type,
    r_party_id_expiration_date, r_party_id_issue_date, r_party_id_issuer_country,
    r_party_id_issuing_agency, r_party_id_issuing_authority_1, r_party_id_number,
    r_party_id_type, r_party_issuing_authority, r_party_mobile_phone, r_party_name,
    r_party_name_1, r_party_name_2, r_party_name_3, r_party_name_4,
    r_party_nationality, r_party_nature_of_work, r_party_occupation,
    r_party_pcp_number, r_party_phone_number, r_party_place_of_birth,
    r_party_relationship, r_party_state_province, r_party_status_of_employment,
    r_party_zipcode_postalcode, r_province, r_purpose_of_transaction, r_routing_number,
    r_source_of_funds, r_template, r_time, r_us_principal, refund_flag,
    s3_party_address_line_2, s3_party_city, s3_party_country, s3_party_date_of_birth,
    s3_party_id_number, s3_party_indorgflag, s3_party_name, s3_party_name_1,
    s3_party_name_2, s3_party_name_3, s3_party_nationality, s3_party_occupation,
    s3_party_phone_number, s3_party_place_of_birth, s3_party_state, s3_party_zip_code,
    s_3rd_party_address_line_1, s_act_on_others_behalf, s_act_on_own_behalf,
    s_agent_country, s_agent_id, s_agent_network_id, s_agent_operator_name_1,
    s_agent_operator_name_2, s_agent_operator_name_3, s_attempt_id, s_bank_city,
    s_bank_code, s_bank_name, s_city, s_counter_party_address_line_1,
    s_counter_party_address_line_2, s_counter_party_city, s_counter_party_country,
    s_counter_party_state, s_counter_party_zipcode_postalcode, s_cpc_currency_code,
    s_currency, s_date, s_electronic_validation, s_fx_feed_date, s_fx_feed_id,
    s_intended_bank_city, s_intended_bank_code, s_intended_bank_name, s_intended_city,
    s_intended_country, s_intended_party_address_line_1,
    s_intended_party_address_line_2, s_intended_party_bank_acct_num,
    s_intended_party_city, s_intended_party_country_of_res,
    s_intended_party_email_address, s_intended_party_mobile_phone,
    s_intended_party_name, s_intended_party_name_1, s_intended_party_name_2,
    s_intended_party_name_3, s_intended_party_name_4, s_intended_party_state_province,
    s_intended_party_zipcode_postalcode, s_intended_routing_number, s_ip_address,
    s_local_charges, s_local_principal, s_party_address_line_1, s_party_address_line_2,
    s_party_bank_account_number, s_party_base_mobile_phone,
    s_party_base_mobile_phone_prefix, s_party_base_phone_number,
    s_party_base_phone_number_prefix, s_party_cc_number, s_party_city,
    s_party_city_of_birth, s_party_country_of_birth, s_party_country_of_residence,
    s_party_date_of_birth, s_party_email_address, s_party_employer,
    s_party_galactic_id, s_party_gender, s_party_id2_exp_date, s_party_id2_issue_date,
    s_party_id2_issuing_country, s_party_id2_number, s_party_id2type,
    s_party_id3_number, s_party_id3type, s_party_id_expiration_date,
    s_party_id_issue_date, s_party_id_issuer_country, s_party_id_issuing_agency,
    s_party_id_issuing_authority_1, s_party_id_number, s_party_id_type,
    s_party_issuing_authority, s_party_mobile_phone, s_party_name, s_party_name_1,
    s_party_name_2, s_party_name_3, s_party_name_4, s_party_nationality,
    s_party_nature_of_work, s_party_occupation, s_party_pcp_number,
    s_party_phone_number, s_party_place_of_birth, s_party_relationship,
    s_party_state_province, s_party_status_of_employment, s_party_zipcode_postalcode,
    s_province, s_purpose_of_transaction, s_routing_number, s_source_of_funds,
    s_template, s_time, s_us_charges, s_us_principal, sub_status, txn_status,
    urb_force_pay_flag, urb_indicator, created_timestamp, modified_timestamp,
    s_party_addr_verif_doc_issuing_authority, r_party_addr_verif_doc_issuing_authority,
    s_party_addr_verif_doc_issue_date, r_party_addr_verif_doc_issue_date,
    s_party_addr_verif_doc_number, r_party_addr_verif_doc_number,
    s_party_addr_verif_doc_type, r_party_addr_verif_doc_type,
    s_party_id2_issuer_authority, r_party_id2_issuer_authority,
    s_party_id3_issuing_country, r_party_id3_issuing_country, s_party_id3_issue_date,
    r_party_id3_issue_date, s_party_id3_exp_date, r_party_id3_exp_date,
    s_party_id3_issuer_authority, r_party_id3_issuer_authority,
    s_intended_party_base_phone_number_prefix, s_intended_party_base_phone_number,
    s_intended_party_base_mobile_phone_prefix, s_intended_party_base_mobile_phone,
    s_intended_party_phone_number, s_intended_agent_country,
    s_intended_party_occupation, s_intended_party_nationality,
    s_intended_party_galactic_id, s_intended_party_date_of_birth,
    r_party_bank_account_type, s_account_holder_name, r_account_holder_name,
    s_intended_account_holder_name, s_merchant_id, r_merchant_id, s_merchant_cat,
    r_merchant_cat, s_merchant_name, r_merchant_name, s_merchant_address,
    r_merchant_address, s_merchant_city, r_merchant_city, s_merchant_state,
    r_merchant_state, s_merchant_zip, r_merchant_zip, s_merchant_country,
    r_merchant_country, s_txn_desc_1, r_txn_desc_1, s_txn_desc_2, r_txn_desc_2,
    transaction_code, transaction_number, s_intended_party_bank_name,
    s_intended_party_bank_city, s_intended_party_routing_number, s_wueco_flag,
    r_wueco_flag, s_state_of_birth, r_state_of_birth, s_bank_account_number_2,
    r_bank_account_number_2
) VALUES (
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s
)
ON CONFLICT (txn_sur_key) DO UPDATE SET
    associated_mtcn = EXCLUDED.associated_mtcn,
    associated_txn_sur_key = EXCLUDED.associated_txn_sur_key,
    bl_customer_verification_source = EXCLUDED.bl_customer_verification_source,
    group_mtcn = EXCLUDED.group_mtcn,
    group_send_date = EXCLUDED.group_send_date,
    latest_attempt_time = EXCLUDED.latest_attempt_time,
    mtcn = EXCLUDED.mtcn,
    mtcn10 = EXCLUDED.mtcn10,
    pa_intended_pay_out = EXCLUDED.pa_intended_pay_out,
    pa_pay_brand = EXCLUDED.pa_pay_brand,
    pa_pay_channel = EXCLUDED.pa_pay_channel,
    pa_pay_in = EXCLUDED.pa_pay_in,
    pa_pay_out = EXCLUDED.pa_pay_out,
    pa_pay_product_code = EXCLUDED.pa_pay_product_code,
    pa_product = EXCLUDED.pa_product,
    pa_recording_channel = EXCLUDED.pa_recording_channel,
    pa_send_brand = EXCLUDED.pa_send_brand,
    pa_send_product_code = EXCLUDED.pa_send_product_code,
    pa_send_speed_of_delivery = EXCLUDED.pa_send_speed_of_delivery,
    r3_party_address_line_2 = EXCLUDED.r3_party_address_line_2,
    r3_party_city = EXCLUDED.r3_party_city,
    r3_party_country = EXCLUDED.r3_party_country,
    r3_party_date_of_birth = EXCLUDED.r3_party_date_of_birth,
    r3_party_id_number = EXCLUDED.r3_party_id_number,
    r3_party_indorgflag = EXCLUDED.r3_party_indorgflag,
    r3_party_name = EXCLUDED.r3_party_name,
    r3_party_name_1 = EXCLUDED.r3_party_name_1,
    r3_party_name_2 = EXCLUDED.r3_party_name_2,
    r3_party_name_3 = EXCLUDED.r3_party_name_3,
    r3_party_nationality = EXCLUDED.r3_party_nationality,
    r3_party_occupation = EXCLUDED.r3_party_occupation,
    r3_party_phone_number = EXCLUDED.r3_party_phone_number,
    r3_party_place_of_birth = EXCLUDED.r3_party_place_of_birth,
    r3_party_state = EXCLUDED.r3_party_state,
    r3_party_zip_code = EXCLUDED.r3_party_zip_code,
    r_3rd_party_address_line_1 = EXCLUDED.r_3rd_party_address_line_1,
    r_act_on_others_behalf = EXCLUDED.r_act_on_others_behalf,
    r_act_on_own_behalf = EXCLUDED.r_act_on_own_behalf,
    r_agent_country = EXCLUDED.r_agent_country,
    r_agent_id = EXCLUDED.r_agent_id,
    r_agent_network_id = EXCLUDED.r_agent_network_id,
    r_agent_operator_name_1 = EXCLUDED.r_agent_operator_name_1,
    r_agent_operator_name_2 = EXCLUDED.r_agent_operator_name_2,
    r_agent_operator_name_3 = EXCLUDED.r_agent_operator_name_3,
    r_attempt_id = EXCLUDED.r_attempt_id,
    r_bank_city = EXCLUDED.r_bank_city,
    r_bank_code = EXCLUDED.r_bank_code,
    r_bank_name = EXCLUDED.r_bank_name,
    r_city = EXCLUDED.r_city,
    r_cpc_currency_code = EXCLUDED.r_cpc_currency_code,
    r_currency = EXCLUDED.r_currency,
    r_date = EXCLUDED.r_date,
    r_electronic_validation = EXCLUDED.r_electronic_validation,
    r_fx_feed_date = EXCLUDED.r_fx_feed_date,
    r_fx_feed_id = EXCLUDED.r_fx_feed_id,
    r_ip_address = EXCLUDED.r_ip_address,
    r_local_principal = EXCLUDED.r_local_principal,
    r_party_address_line_1 = EXCLUDED.r_party_address_line_1,
    r_party_address_line_2 = EXCLUDED.r_party_address_line_2,
    r_party_bank_account_number = EXCLUDED.r_party_bank_account_number,
    r_party_base_mobile_phone = EXCLUDED.r_party_base_mobile_phone,
    r_party_base_mobile_phone_prefix = EXCLUDED.r_party_base_mobile_phone_prefix,
    r_party_base_phone_number = EXCLUDED.r_party_base_phone_number,
    r_party_base_phone_number_prefix = EXCLUDED.r_party_base_phone_number_prefix,
    r_party_city = EXCLUDED.r_party_city,
    r_party_city_of_birth = EXCLUDED.r_party_city_of_birth,
    r_party_country_of_birth = EXCLUDED.r_party_country_of_birth,
    r_party_country_of_residence = EXCLUDED.r_party_country_of_residence,
    r_party_date_of_birth = EXCLUDED.r_party_date_of_birth,
    r_party_email_address = EXCLUDED.r_party_email_address,
    r_party_employer = EXCLUDED.r_party_employer,
    r_party_galactic_id = EXCLUDED.r_party_galactic_id,
    r_party_gender = EXCLUDED.r_party_gender,
    r_party_id2_exp_date = EXCLUDED.r_party_id2_exp_date,
    r_party_id2_issue_date = EXCLUDED.r_party_id2_issue_date,
    r_party_id2_issuing_country = EXCLUDED.r_party_id2_issuing_country,
    r_party_id2_number = EXCLUDED.r_party_id2_number,
    r_party_id2type = EXCLUDED.r_party_id2type,
    r_party_id3_number = EXCLUDED.r_party_id3_number,
    r_party_id3type = EXCLUDED.r_party_id3type,
    r_party_id_expiration_date = EXCLUDED.r_party_id_expiration_date,
    r_party_id_issue_date = EXCLUDED.r_party_id_issue_date,
    r_party_id_issuer_country = EXCLUDED.r_party_id_issuer_country,
    r_party_id_issuing_agency = EXCLUDED.r_party_id_issuing_agency,
    r_party_id_issuing_authority_1 = EXCLUDED.r_party_id_issuing_authority_1,
    r_party_id_number = EXCLUDED.r_party_id_number,
    r_party_id_type = EXCLUDED.r_party_id_type,
    r_party_issuing_authority = EXCLUDED.r_party_issuing_authority,
    r_party_mobile_phone = EXCLUDED.r_party_mobile_phone,
    r_party_name = EXCLUDED.r_party_name,
    r_party_name_1 = EXCLUDED.r_party_name_1,
    r_party_name_2 = EXCLUDED.r_party_name_2,
    r_party_name_3 = EXCLUDED.r_party_name_3,
    r_party_name_4 = EXCLUDED.r_party_name_4,
    r_party_nationality = EXCLUDED.r_party_nationality,
    r_party_nature_of_work = EXCLUDED.r_party_nature_of_work,
    r_party_occupation = EXCLUDED.r_party_occupation,
    r_party_pcp_number = EXCLUDED.r_party_pcp_number,
    r_party_phone_number = EXCLUDED.r_party_phone_number,
    r_party_place_of_birth = EXCLUDED.r_party_place_of_birth,
    r_party_relationship = EXCLUDED.r_party_relationship,
    r_party_state_province = EXCLUDED.r_party_state_province,
    r_party_status_of_employment = EXCLUDED.r_party_status_of_employment,
    r_party_zipcode_postalcode = EXCLUDED.r_party_zipcode_postalcode,
    r_province = EXCLUDED.r_province,
    r_purpose_of_transaction = EXCLUDED.r_purpose_of_transaction,
    r_routing_number = EXCLUDED.r_routing_number,
    r_source_of_funds = EXCLUDED.r_source_of_funds,
    r_template = EXCLUDED.r_template,
    r_time = EXCLUDED.r_time,
    r_us_principal = EXCLUDED.r_us_principal,
    refund_flag = EXCLUDED.refund_flag,
    s3_party_address_line_2 = EXCLUDED.s3_party_address_line_2,
    s3_party_city = EXCLUDED.s3_party_city,
    s3_party_country = EXCLUDED.s3_party_country,
    s3_party_date_of_birth = EXCLUDED.s3_party_date_of_birth,
    s3_party_id_number = EXCLUDED.s3_party_id_number,
    s3_party_indorgflag = EXCLUDED.s3_party_indorgflag,
    s3_party_name = EXCLUDED.s3_party_name,
    s3_party_name_1 = EXCLUDED.s3_party_name_1,
    s3_party_name_2 = EXCLUDED.s3_party_name_2,
    s3_party_name_3 = EXCLUDED.s3_party_name_3,
    s3_party_nationality = EXCLUDED.s3_party_nationality,
    s3_party_occupation = EXCLUDED.s3_party_occupation,
    s3_party_phone_number = EXCLUDED.s3_party_phone_number,
    s3_party_place_of_birth = EXCLUDED.s3_party_place_of_birth,
    s3_party_state = EXCLUDED.s3_party_state,
    s3_party_zip_code = EXCLUDED.s3_party_zip_code,
    s_3rd_party_address_line_1 = EXCLUDED.s_3rd_party_address_line_1,
    s_act_on_others_behalf = EXCLUDED.s_act_on_others_behalf,
    s_act_on_own_behalf = EXCLUDED.s_act_on_own_behalf,
    s_agent_country = EXCLUDED.s_agent_country,
    s_agent_id = EXCLUDED.s_agent_id,
    s_agent_network_id = EXCLUDED.s_agent_network_id,
    s_agent_operator_name_1 = EXCLUDED.s_agent_operator_name_1,
    s_agent_operator_name_2 = EXCLUDED.s_agent_operator_name_2,
    s_agent_operator_name_3 = EXCLUDED.s_agent_operator_name_3,
    s_attempt_id = EXCLUDED.s_attempt_id,
    s_bank_city = EXCLUDED.s_bank_city,
    s_bank_code = EXCLUDED.s_bank_code,
    s_bank_name = EXCLUDED.s_bank_name,
    s_city = EXCLUDED.s_city,
    s_counter_party_address_line_1 = EXCLUDED.s_counter_party_address_line_1,
    s_counter_party_address_line_2 = EXCLUDED.s_counter_party_address_line_2,
    s_counter_party_city = EXCLUDED.s_counter_party_city,
    s_counter_party_country = EXCLUDED.s_counter_party_country,
    s_counter_party_state = EXCLUDED.s_counter_party_state,
    s_counter_party_zipcode_postalcode = EXCLUDED.s_counter_party_zipcode_postalcode,
    s_cpc_currency_code = EXCLUDED.s_cpc_currency_code,
    s_currency = EXCLUDED.s_currency,
    s_date = EXCLUDED.s_date,
    s_electronic_validation = EXCLUDED.s_electronic_validation,
    s_fx_feed_date = EXCLUDED.s_fx_feed_date,
    s_fx_feed_id = EXCLUDED.s_fx_feed_id,
    s_intended_bank_city = EXCLUDED.s_intended_bank_city,
    s_intended_bank_code = EXCLUDED.s_intended_bank_code,
    s_intended_bank_name = EXCLUDED.s_intended_bank_name,
    s_intended_city = EXCLUDED.s_intended_city,
    s_intended_country = EXCLUDED.s_intended_country,
    s_intended_party_address_line_1 = EXCLUDED.s_intended_party_address_line_1,
    s_intended_party_address_line_2 = EXCLUDED.s_intended_party_address_line_2,
    s_intended_party_bank_acct_num = EXCLUDED.s_intended_party_bank_acct_num,
    s_intended_party_city = EXCLUDED.s_intended_party_city,
    s_intended_party_country_of_res = EXCLUDED.s_intended_party_country_of_res,
    s_intended_party_email_address = EXCLUDED.s_intended_party_email_address,
    s_intended_party_mobile_phone = EXCLUDED.s_intended_party_mobile_phone,
    s_intended_party_name = EXCLUDED.s_intended_party_name,
    s_intended_party_name_1 = EXCLUDED.s_intended_party_name_1,
    s_intended_party_name_2 = EXCLUDED.s_intended_party_name_2,
    s_intended_party_name_3 = EXCLUDED.s_intended_party_name_3,
    s_intended_party_name_4 = EXCLUDED.s_intended_party_name_4,
    s_intended_party_state_province = EXCLUDED.s_intended_party_state_province,
    s_intended_party_zipcode_postalcode = EXCLUDED.s_intended_party_zipcode_postalcode,
    s_intended_routing_number = EXCLUDED.s_intended_routing_number,
    s_ip_address = EXCLUDED.s_ip_address,
    s_local_charges = EXCLUDED.s_local_charges,
    s_local_principal = EXCLUDED.s_local_principal,
    s_party_address_line_1 = EXCLUDED.s_party_address_line_1,
    s_party_address_line_2 = EXCLUDED.s_party_address_line_2,
    s_party_bank_account_number = EXCLUDED.s_party_bank_account_number,
    s_party_base_mobile_phone = EXCLUDED.s_party_base_mobile_phone,
    s_party_base_mobile_phone_prefix = EXCLUDED.s_party_base_mobile_phone_prefix,
    s_party_base_phone_number = EXCLUDED.s_party_base_phone_number,
    s_party_base_phone_number_prefix = EXCLUDED.s_party_base_phone_number_prefix,
    s_party_cc_number = EXCLUDED.s_party_cc_number,
    s_party_city = EXCLUDED.s_party_city,
    s_party_city_of_birth = EXCLUDED.s_party_city_of_birth,
    s_party_country_of_birth = EXCLUDED.s_party_country_of_birth,
    s_party_country_of_residence = EXCLUDED.s_party_country_of_residence,
    s_party_date_of_birth = EXCLUDED.s_party_date_of_birth,
    s_party_email_address = EXCLUDED.s_party_email_address,
    s_party_employer = EXCLUDED.s_party_employer,
    s_party_galactic_id = EXCLUDED.s_party_galactic_id,
    s_party_gender = EXCLUDED.s_party_gender,
    s_party_id2_exp_date = EXCLUDED.s_party_id2_exp_date,
    s_party_id2_issue_date = EXCLUDED.s_party_id2_issue_date,
    s_party_id2_issuing_country = EXCLUDED.s_party_id2_issuing_country,
    s_party_id2_number = EXCLUDED.s_party_id2_number,
    s_party_id2type = EXCLUDED.s_party_id2type,
    s_party_id3_number = EXCLUDED.s_party_id3_number,
    s_party_id3type = EXCLUDED.s_party_id3type,
    s_party_id_expiration_date = EXCLUDED.s_party_id_expiration_date,
    s_party_id_issue_date = EXCLUDED.s_party_id_issue_date,
    s_party_id_issuer_country = EXCLUDED.s_party_id_issuer_country,
    s_party_id_issuing_agency = EXCLUDED.s_party_id_issuing_agency,
    s_party_id_issuing_authority_1 = EXCLUDED.s_party_id_issuing_authority_1,
    s_party_id_number = EXCLUDED.s_party_id_number,
    s_party_id_type = EXCLUDED.s_party_id_type,
    s_party_issuing_authority = EXCLUDED.s_party_issuing_authority,
    s_party_mobile_phone = EXCLUDED.s_party_mobile_phone,
    s_party_name = EXCLUDED.s_party_name,
    s_party_name_1 = EXCLUDED.s_party_name_1,
    s_party_name_2 = EXCLUDED.s_party_name_2,
    s_party_name_3 = EXCLUDED.s_party_name_3,
    s_party_name_4 = EXCLUDED.s_party_name_4,
    s_party_nationality = EXCLUDED.s_party_nationality,
    s_party_nature_of_work = EXCLUDED.s_party_nature_of_work,
    s_party_occupation = EXCLUDED.s_party_occupation,
    s_party_pcp_number = EXCLUDED.s_party_pcp_number,
    s_party_phone_number = EXCLUDED.s_party_phone_number,
    s_party_place_of_birth = EXCLUDED.s_party_place_of_birth,
    s_party_relationship = EXCLUDED.s_party_relationship,
    s_party_state_province = EXCLUDED.s_party_state_province,
    s_party_status_of_employment = EXCLUDED.s_party_status_of_employment,
    s_party_zipcode_postalcode = EXCLUDED.s_party_zipcode_postalcode,
    s_province = EXCLUDED.s_province,
    s_purpose_of_transaction = EXCLUDED.s_purpose_of_transaction,
    s_routing_number = EXCLUDED.s_routing_number,
    s_source_of_funds = EXCLUDED.s_source_of_funds,
    s_template = EXCLUDED.s_template,
    s_time = EXCLUDED.s_time,
    s_us_charges = EXCLUDED.s_us_charges,
    s_us_principal = EXCLUDED.s_us_principal,
    sub_status = EXCLUDED.sub_status,
    txn_status = EXCLUDED.txn_status,
    urb_force_pay_flag = EXCLUDED.urb_force_pay_flag,
    urb_indicator = EXCLUDED.urb_indicator,
    created_timestamp = EXCLUDED.created_timestamp,
    modified_timestamp = EXCLUDED.modified_timestamp,
    s_party_addr_verif_doc_issuing_authority = EXCLUDED.s_party_addr_verif_doc_issuing_authority,
    r_party_addr_verif_doc_issuing_authority = EXCLUDED.r_party_addr_verif_doc_issuing_authority,
    s_party_addr_verif_doc_issue_date = EXCLUDED.s_party_addr_verif_doc_issue_date,
    r_party_addr_verif_doc_issue_date = EXCLUDED.r_party_addr_verif_doc_issue_date,
    s_party_addr_verif_doc_number = EXCLUDED.s_party_addr_verif_doc_number,
    r_party_addr_verif_doc_number = EXCLUDED.r_party_addr_verif_doc_number,
    s_party_addr_verif_doc_type = EXCLUDED.s_party_addr_verif_doc_type,
    r_party_addr_verif_doc_type = EXCLUDED.r_party_addr_verif_doc_type,
    s_party_id2_issuer_authority = EXCLUDED.s_party_id2_issuer_authority,
    r_party_id2_issuer_authority = EXCLUDED.r_party_id2_issuer_authority,
    s_party_id3_issuing_country = EXCLUDED.s_party_id3_issuing_country,
    r_party_id3_issuing_country = EXCLUDED.r_party_id3_issuing_country,
    s_party_id3_issue_date = EXCLUDED.s_party_id3_issue_date,
    r_party_id3_issue_date = EXCLUDED.r_party_id3_issue_date,
    s_party_id3_exp_date = EXCLUDED.s_party_id3_exp_date,
    r_party_id3_exp_date = EXCLUDED.r_party_id3_exp_date,
    s_party_id3_issuer_authority = EXCLUDED.s_party_id3_issuer_authority,
    r_party_id3_issuer_authority = EXCLUDED.r_party_id3_issuer_authority,
    s_intended_party_base_phone_number_prefix = EXCLUDED.s_intended_party_base_phone_number_prefix,
    s_intended_party_base_phone_number = EXCLUDED.s_intended_party_base_phone_number,
    s_intended_party_base_mobile_phone_prefix = EXCLUDED.s_intended_party_base_mobile_phone_prefix,
    s_intended_party_base_mobile_phone = EXCLUDED.s_intended_party_base_mobile_phone,
    s_intended_party_phone_number = EXCLUDED.s_intended_party_phone_number,
    s_intended_agent_country = EXCLUDED.s_intended_agent_country,
    s_intended_party_occupation = EXCLUDED.s_intended_party_occupation,
    s_intended_party_nationality = EXCLUDED.s_intended_party_nationality,
    s_intended_party_galactic_id = EXCLUDED.s_intended_party_galactic_id,
    s_intended_party_date_of_birth = EXCLUDED.s_intended_party_date_of_birth,
    r_party_bank_account_type = EXCLUDED.r_party_bank_account_type,
    s_account_holder_name = EXCLUDED.s_account_holder_name,
    r_account_holder_name = EXCLUDED.r_account_holder_name,
    s_intended_account_holder_name = EXCLUDED.s_intended_account_holder_name,
    s_merchant_id = EXCLUDED.s_merchant_id,
    r_merchant_id = EXCLUDED.r_merchant_id,
    s_merchant_cat = EXCLUDED.s_merchant_cat,
    r_merchant_cat = EXCLUDED.r_merchant_cat,
    s_merchant_name = EXCLUDED.s_merchant_name,
    r_merchant_name = EXCLUDED.r_merchant_name,
    s_merchant_address = EXCLUDED.s_merchant_address,
    r_merchant_address = EXCLUDED.r_merchant_address,
    s_merchant_city = EXCLUDED.s_merchant_city,
    r_merchant_city = EXCLUDED.r_merchant_city,
    s_merchant_state = EXCLUDED.s_merchant_state,
    r_merchant_state = EXCLUDED.r_merchant_state,
    s_merchant_zip = EXCLUDED.s_merchant_zip,
    r_merchant_zip = EXCLUDED.r_merchant_zip,
    s_merchant_country = EXCLUDED.s_merchant_country,
    r_merchant_country = EXCLUDED.r_merchant_country,
    s_txn_desc_1 = EXCLUDED.s_txn_desc_1,
    r_txn_desc_1 = EXCLUDED.r_txn_desc_1,
    s_txn_desc_2 = EXCLUDED.s_txn_desc_2,
    r_txn_desc_2 = EXCLUDED.r_txn_desc_2,
    transaction_code = EXCLUDED.transaction_code,
    transaction_number = EXCLUDED.transaction_number,
    s_intended_party_bank_name = EXCLUDED.s_intended_party_bank_name,
    s_intended_party_bank_city = EXCLUDED.s_intended_party_bank_city,
    s_intended_party_routing_number = EXCLUDED.s_intended_party_routing_number,
    s_wueco_flag = EXCLUDED.s_wueco_flag,
    r_wueco_flag = EXCLUDED.r_wueco_flag,
    s_state_of_birth = EXCLUDED.s_state_of_birth,
    r_state_of_birth = EXCLUDED.r_state_of_birth,
    s_bank_account_number_2 = EXCLUDED.s_bank_account_number_2,
    r_bank_account_number_2 = EXCLUDED.r_bank_account_number_2
"""


def to_values(row: dict) -> tuple:
    return tuple(row.get(column) for column in COLUMNS)


def main() -> None:
    parser = build_parser("Load reg_reportable_activity mock data", DEFAULT_FILE)
    args = parser.parse_args()
    rows = read_json_rows(args.file, REQUIRED_COLUMNS)
    run_loader(args=args, rows=rows, table=TABLE, statement=UPSERT, to_values=to_values)


if __name__ == "__main__":
    main()
